export const stateAddActive = {
  addButtonStyle: {
    padding: 0,
    height: 80,
    width: 80,
    border: "none",
    cursor: "pointer",
    background: "#fff",
  },
  addSpacerStyle: {
    padding: 0,
    height: 80,
    width: 80,
    background: "#fff",
    color: "#8A2EE8",
  },
  styleButtonStyle: {
    padding: 0,
    height: 80,
    width: 80,
    border: "none",
    cursor: "pointer",
    background: "#fff",
  },
  styleSpacerStyle: {
    padding: 0,
    height: 80,
    width: 80,
    background: "#F6F6F4",
    borderRadius: "0px 10px 0px 0px",
    boxShadow: "-5px 5px 8px 0px rgba(0, 0, 0, 0.05) inset",
  },
  emptyOuterDivStyle: {
    padding: 0,
    background: "#F6F6F4",
    height: 80,
    width: 80,
  },
  emptyInnerDivStyle: {
    padding: 0,
    height: 80,
    width: 80,
    background: "#F6F6F4",
    boxShadow: "-25px -10px 8px -20px rgba(0, 0, 0, 0.05) inset",
  },
};

export const stateStyleActive = {
  addButtonStyle: {
    padding: 0,
    height: 80,
    width: 80,
    border: "none",
    cursor: "pointer",
    background: "#fff",
  },
  addSpacerStyle: {
    padding: 0,
    height: 80,
    width: 80,
    background: "#F6F6F4",
    borderRadius: "0px 0px 10px 0px",
    boxShadow: "-5px 0px 8px 0px rgba(0, 0, 0, 0.05) inset",
  },
  styleButtonStyle: {
    padding: 0,
    height: 80,
    width: 80,
    border: "none",
    cursor: "pointer",
    background: "#fff",
  },
  styleSpacerStyle: {
    padding: 0,
    height: 80,
    width: 80,
    background: "#fff",
    color: "#8A2EE8",
  },
  emptyOuterDivStyle: {
    padding: 0,
    background: "#fff",
    height: 80,
    width: 80,
  },
  emptyInnerDivStyle: {
    padding: 0,
    height: 80,
    width: 80,
    background: "#F6F6F4",
    borderRadius: "0px 10px 0px 0px",
    boxShadow: "-5px 6px 8px 0px rgba(0, 0, 0, 0.05) inset",
  },
};